#cloud-config
write_files:
  - path: /home/ec2-user/.env
    owner: ec2-user:ec2-user
    permissions: "0644"
    content: |
      DATABASE_URL="mysql://${db_user}:${db_pass}@${db_url}/${db_name}"
runcmd:
  - [ cd, /home/ec2-user]
  - [ npx, prisma, migrate, deploy]
  - [ npx, prisma, generate ]
  - [ systemctl, restart, --no-block, trackify.service ]